err now prefixes message with "Error: "

diff --git a/ello-jail b/ello-jail
--- a/ello-jail
+++ b/ello-jail
@@ -5,7 +5,7 @@ readonly CONFIG_LOCATION=/usr/local/etc/ello-jail
 
 
 err() {
-    echo $1 1>&2
+    echo "Error: " $@ 1>&2
     exit 1
 }
 
